### ISSUE TITLE
iFLO and HAiFLO return NA

### ISSUE THREAD

**Issue by p-schaefer** [GLFC-WET/hydroweight#7]
Hi Brian,

 Enjoying the package so far. I'm having a bit of trouble with ```hydroweight()``` occasionally returning NAs for only some of my sites, for iFLO and HAiFLO.  I'm uploading the files to onedrive now and will provide a download link with the files that are producing the errors shortly, but its very odd because there is a site just a bit further down stream that works just fine.  

Any ideas about why this may be happening?

Thanks,
Patrick

**Comment by bkielstr** [comment]
Hi @p-schaefer - sorry about the late reply and thanks for checking out hydroweight and using it in your work. 

From the files you sent privately, it looks like ```hydroweight```'s internal ```whitebox::wbt_clip_raster_to_polygons()``` on the ```dem```, which is used to produce ```iFLO``` and ```HAiFLO```, misses the cells that your sampling site is on. This is strange but is an unfortunate boundary issue when clipping. With ```target_O``` being outside of the clipped ```dem```, that is why you had an ```NA``` result. I'm going to consider rasterizing the ```clip_region.shp``` first instead of doing the direct clip as a result of this.  

As a solution for now, your ```clip_region.shp``` looks like a watershed. What I would suggest is that you build a buffer of say 1000 m around ```clip_region.shp``` and use that new buffer as ```clip_region``` in ```hydroweight()```. If you're interested in using the ```clip_region.shp``` to calculate the attributes, then use that as your ```roi```. Even if regions are calculated using ```hydroweight()```, they are discarded from calculations an ```roi``` is included in ```hydroweight_attributes()``` 

![image](https://user-images.githubusercontent.com/14337757/131175065-04a9314b-7650-474e-ad6a-55b427e943cc.png)

**Comment by p-schaefer** [comment]
Thank for following up.

I've tried adding a buffer using `st_buffer()` on one of the sites where the weighting schemes did not produce NAs, and I ended up with different `hydroweight_attributes()` when the weighting scheme included a buffer, vs when it didn't. To be clear, I applied the buffer to the `clip_region` when running `hydroweight()`, but did not apply the buffer when running `hydroweight_attributes()`. They didn't differ by much (on the scale of about 0.001), but just wanted to confirm that that is what you meant.

**Comment by bkielstr** [comment]
By site, you mean ```clip_region.shp```, right? 

The ```dem``` clipping by ```clip_region``` is really meant to improve processing times in subsequent operations. As you know (judging by you *not* using the buffered ```clip_region.shp``` in ```hydroweight_attributes()```), it is ok to have generated weights outside of "true" watershed boundary of your site. Those weights will be discarded when you calculate attributes in your ```roi``` using ```hydroweight_attributes()```. 

Any differences in the calculated attributes are likely related to the same unfortunate clipping issue but may have been in another portion of the watershed this time. For sites where iFLO and HAiFLO worked before (because the sampling point was not missed by the clipping operation), another portion of the watershed may have had the same boundary issue. It is best to have a slightly larger region feeding the output of ```hydroweight()``` and then use ```roi`` for the attributes. 

I will need to work on minimizing the number of clips/rasterization steps to avoid these boundary issues but my decision early on was to have every external input converted into the DEM grain by nearest neighbour (categorical) or bilinear interpolation (numeric) but am considering having more options available.

**Comment by bkielstr** [comment]
@p-schaefer - does the answer seem reasonable enough to close this issue?

**Comment by p-schaefer** [comment]
@bkielstr Yes, thanks! Once again, thank you for putting this package together. Its a much needed addition to the world of stream research and monitoring.
